

Class_42_02_ExceptionHandling.py
try:
    print(1 / 0)  # ZeroDivisionError: division by zero
except:
    print("Exception is caught")
print("the end")

